dispanel/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('panel/', views.dispatcher_panel, name='dispatcher_panel'),
    path('logout/', views.logout_view, name='logout'),
    path('<int:pk>/', views.PanelDisplay.as_view(), name='message_details'),
    path('<int:pk>/delete', views.MessageDelete.as_view(), name='message_delete')
]

main/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.index)
]

message/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('create/',views.message_text, name='create'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('dispanel/',include('dispanel.urls')),
    path('messages/',include('message.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

message/models.py
from django.db import models
from django.utils import timezone
class Messages(models.Model):
    MES_STATUS=[('new', 'Новое'),
                ('read', 'Прочитано')
                 ]
    TITLE_STATUS=[('Choose theme','Выберите тему'),
                  ('Fire','Пожар'),
                  ('Fire in the forest','Пожар в лесу'),
                  ('Road repairs','Ремонт дорог'), 
                  ('Clean garbage','Убрать мусор'),
                  ('Street light','Уличное освещение'),
                  ('Other','Смотрите тему ниже')]
    title = models.CharField('Тема', max_length=50, choices=TITLE_STATUS, default='Choose theme')
    mes_text=models.TextField('Сообщение', max_length=500)
    ent_mail=models.CharField('Почта',max_length=50)
    latitude = models.FloatField('Широта', default='0.0')
    longitude = models.FloatField('Долгота', default='0.0')
    created_at = models.DateTimeField(auto_now_add=True)
    status=models.CharField(max_length=5, choices=MES_STATUS, default='new')  
    def __str__(self):
        return self.title
    class Meta:
        verbose_name='Сообщение'
        verbose_name_plural='Сообщения'

dispanel/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 
        'style': 'width: 400px; margin-left: 39.9%',
        'placeholder': 'Логин'
        }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control', 
        'style': 'width: 400px; margin-left: 39.9%',
        'placeholder': 'Пароль' 
        }))

message/forms.py
from .models import Messages
from django.forms import ModelForm, TextInput, Textarea

class MessagesForm(ModelForm):
    class Meta:
        model=Messages
        fields=['title', 'mes_text', 'ent_mail', 'latitude','longitude']
        widgets={
            'ent_mail': TextInput(attrs={
                'class':'form-control',
                'placeholder':'вашапочта@mail.ru (пример)',
                'required': 'required'
            }),
            'mes_text': Textarea(attrs={
                'class':'form-control',
                'style':'min-height: 100px; max-height: 300px;',
                'placeholder':'Опишите вашу проблему',
                'required': 'required'
            }),
            'latitude': TextInput(attrs={
                'class': 'form-control',
                'style': 'width: 100px',
                'readonly': 'readonly',
                'placeholder': 'Кликните на карту',
                'required': 'required'
            }),
            'longitude': TextInput(attrs={
                'class': 'form-control',
                'style': 'width: 100px',
                'readonly': 'readonly', 
                'placeholder': 'Кликните на карту',
                'required': 'required'
            }),
        }

dispanel/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .forms import LoginForm
from message.models import Messages
from django.views.generic import DetailView, DeleteView

def login_view(request):
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('dispatcher_panel') 
    else:
        form = LoginForm()

    return render(request, 'dispanel/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('login')

@login_required
def dispatcher_panel(request):
    new_messages =Messages.objects.filter(status='new').order_by('-created_at')
    read_messages = Messages.objects.filter(status='read').order_by('-created_at')
    return render(request, 'dispanel/dispanel_home.html',  {
        'new_messages': new_messages,
        'read_messages': read_messages
    })

class PanelDisplay (DetailView):
    model=Messages
    template_name='dispanel/message_display.html'
    context_object_name='message'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        message = context['message']
        if message.status=='new':
            message.status='read'
            message.save()
        new_messages =Messages.objects.filter(status='new').order_by('-created_at')
        read_messages = Messages.objects.filter(status='read').order_by('-created_at')
        context['new_messages'] = new_messages
        context['read_messages'] = read_messages
        return context
    
class MessageDelete (DeleteView):
    model=Messages
    context_object_name = 'message'
    success_url = reverse_lazy('dispatcher_panel')

main/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'main\slide-main.html')

message/views.py
from django.shortcuts import render, redirect
from .forms import MessagesForm

def message_text(request):
    if request.method=='POST':
        form=MessagesForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:   
        form = MessagesForm()
    return render(request, 'message\make_a_message.html', {'form': form})

dispanel/templates/dispanel/dispanel_home.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="icon" type="image/x-icon" href="{% static 'main\images\envira-brands.svg' %}">
        <title>Панель диспетчера</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <link rel="stylesheet" href="{% static 'main/css/dispanel.css'%}">
        <style>
            .hidden{
                display: none;
            }
        </style>
    </head>
    <body>
        <header class="custom-header py-3 px-5 d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center">
                <i class="fa-solid fa-user fa-3x me-3" style="color: #ffffff;"></i>
                <h1 class="h2 mb-0" style="color: white">Здравствуйте, {{ user.username }}!</h1>
            </div>
            <div class="main-btns">
                <a href="{% url 'logout' %}" class="btn btn-light" style="width: 200px; height: 55px; font-size: 30px; padding: 5px; color: black;">Выйти</a>
            </div>
        </header>
        <main>
            <section class="messages-list">
                <h3>Новые сообщения</h3>
                <div class="new_mess">
                    <div class="readMessages">
                        <button class="btn toggle-btn" style="border-color: black;"><span class="arrow">Скрыть</span></button>
                    
                        {% if new_messages %}
                        <div class="messages-group">
                            {% for msg in new_messages %}
                            <a class="message" href="{% url 'message_details' msg.id %}">
                                <div>
                                    {% if msg.title == 'Other' %}
                                        <strong>{{ msg.mes_text|truncatechars:50 }}</strong>
                                    {% else %}
                                        <strong>{{ msg.get_title_display }}</strong>
                                        <p>{{ msg.mes_text|truncatechars:50 }}</p>
                                    {% endif %}
                                </div>
                                <div class="status error"></div>
                            </a>
                            {% endfor %}
                        </div>
                        {% else %}
                        <div class="mess_empty">
                            <p>Новых сообщений пока нет!</p>
                        </div>
                        {% endif %}
                    </div>
                </div>
                <h3>Прочитанные сообщения</h3>
                <div class="read_mess">
                    <div class="readMessages">
                        <button class="btn toggle-btn" style="border-color: black;"><span class="arrow">Скрыть</span></button>
                    
                        {% if read_messages %}
                        <div class="messages-group">
                            {% for msg in read_messages %}
                            <a class="message" href="{% url 'message_details' msg.id %}">
                                <div>
                                    {% if msg.title == 'Other' %}
                                        <strong>{{ msg.mes_text|truncatechars:50 }}</strong>
                                    {% else %}
                                        <strong>{{ msg.get_title_display }}</strong>
                                        <p>{{ msg.mes_text|truncatechars:50 }}</p>
                                    {% endif %}
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                        {% else %}
                        <div class="mess_empty">
                            <p>Сообщений нет :(</p>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </section>
        </main>
        <script src="{% static 'main/js/main_display.js'%}"></script>
    </body>
</html>

dispanel/templates/dispanel/login.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="icon" type="image/x-icon" href="{% static 'main\images\envira-brands.svg' %}">
        <title>Войти</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <link rel="stylesheet" href="{% static 'main/css/main.css'%}">
    </head>
    <body>
        <header class="custom-header py-3 px-5 d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center">
                <img src="{% static 'main/images/envira-brands.svg' %}" alt="icon" width="80" class="me-3">
                <h1 class="h2 mb-0">Делаем мир лучше</h1>
            </div>
            <div class="main-btns">
                <a href="{% url 'home' %}" class="btn btn-dark" style="width: 200px; height: 55px; font-size: 27px; padding: 5px;">На главную</a>
            </div>
        </header>
        <main>
            <div class="login_form">
                <form method="post">
                    {% csrf_token %}
                    <h1>Имя пользователя:</h1><br>
                    <div>
                        {{ form.username }}
                    </div><br>
                    <h1>Пароль:</h1><br>
                    <div>
                        {{ form.password }}
                    </div><br>
                    <button type="submit" class="btn btn-primary btn-enter">Войти</button><br>
                    {% if form.errors %}
                        <div class="text-danger">Неверный логин или пароль</div>
                    {% endif %}
                </form>
            </div>
        </main>
    </body>
</html>

dispanel/templates/dispanel/message_display.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="icon" type="image/x-icon" href="{% static 'main\images\envira-brands.svg' %}">
        <title>Панель диспетчера</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <link rel="stylesheet" href="{% static 'main/css/dispanel.css' %}">
        <style>
            .hidden{
                display: none;
            }
        </style>
    </head>
    <body>
        <header class="custom-header py-3 px-5 d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center">
                <i class="fa-solid fa-user fa-3x me-3" style="color: #ffffff;"></i>
                <h1 class="h2 mb-0" style="color: white">Здравствуйте, {{ user.username }}!</h1>
            </div>
            <div class="main-btns">
                <a href="{% url 'logout' %}" class="btn btn-light btn-exit" style="width: 200px; height: 55px; font-size: 30px; padding: 5px; color: black;">Выйти</a>
            </div>
        </header>
        <main>
            <section class="messages-list">
                <h3>Новые сообщения</h3>
                <div class="new_mess">
                    <div class="readMessages">
                        <button class="btn toggle-btn" style="border-color: black;"><span class="arrow">Скрыть</span></button>
                    
                        {% if new_messages %}
                        <div class="messages-group">
                            {% for msg in new_messages %}
                            <a class="message" href="{% url 'message_details' msg.id %}">
                                <div>
                                    {% if msg.title == 'Other' %}
                                        <strong>{{ msg.mes_text|truncatechars:50 }}</strong>
                                    {% else %}
                                        <strong>{{ msg.get_title_display }}</strong>
                                        <p>{{ msg.mes_text|truncatechars:50 }}</p>
                                    {% endif %}
                                </div>
                                <div class="status error"></div>
                            </a>
                            {% endfor %}
                        </div>
                        {% else %}
                        <div class="mess_empty">
                            <p>Новых сообщений пока нет!</p>
                        </div>
                        {% endif %}
                    </div>
                </div>
                <h3>Прочитанные сообщения</h3>
                <div class="read_mess">
                    <div class="readMessages">
                        <button class="btn toggle-btn" style="border-color: black;"><span class="arrow">Скрыть</span></button>
                    
                        {% if read_messages %}
                        <div class="messages-group">
                            {% for msg in read_messages %}
                            <a class="message" href="{% url 'message_details' msg.id %}">
                                <div>
                                    {% if msg.title == 'Other' %}
                                        <strong>{{ msg.mes_text|truncatechars:50 }}</strong>
                                    {% else %}
                                        <strong>{{ msg.get_title_display }}</strong>
                                        <p>{{ msg.mes_text|truncatechars:50 }}</p>
                                    {% endif %}
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                        {% else %}
                        <div class="mess_empty">
                            <p>Сообщений нет :(</p>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </section>
            <section class="message-details">
                <h2><strong>Тема</strong></h2>
                <h3>{{message.get_title_display}}</h3>
            
                <h2><strong>Указанная почта</strong></h2>
                <h3>{{message.ent_mail}}</h3>

                <h2><strong>Описание</strong></h2>
                <p>{{message.mes_text}}</p>

                <h2><strong>Координаты</strong></h2>
                <div style="position: flexable; display: flex; gap: 10px; height: 50px;">
                    <p style="max-width: 100px;">Широта: {{message.latitude|truncatechars:10}}</p><br>
                    <p style="max-width: 100px;">Долгота: {{message.longitude|truncatechars:10}}</p>
                    <button id="openYandexMap" class="btn btn-primary"
                        data-latitude="{{ message.latitude|floatformat:"6"|default:"0" }}"
                        data-longitude="{{ message.longitude|floatformat:"6"|default:"0" }}">
                        Показать на карте
                    </button>
                </div><br>
                <div class="buttons">
                    <a href="{% url 'dispatcher_panel' %}" class="btn btn-dark">Закрыть</a>
                    <a href="mailto:{{ message.ent_mail }}" class="btn btn-primary">Написать на почту</a>
                    <a id="openModal" class="btn btn-danger">Удалить сообщение</a>
                </div>
            </section>
        </main>
        <div id="modal" class="modal-overlay">
            <div class="modal-content">
                <h4><b>Вы уверены, что хотите удалить это сообщение?</b></h4><br>
                <form method="POST" action="{% url 'message_delete' message.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger delete-btn">Удалить</button>
                </form>
                <button id="closeModal" class="btn btn-dark close-btn">Отмена</button>
            </div>
        </div>
        <script src="{% static 'main/js/display.js'%}"></script>
    </body>
</html>

main/templates/main/index.html
{% extends 'main/pattern.html' %}

{%block title %} Крысятничество.рф {%endblock%}

{% block content %}
    
{% endblock %}

main/templates/main/slide-main.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="icon" type="image/x-icon" href="{% static 'main\images\envira-brands.svg' %}">
        <title>Главная страница</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <link rel="stylesheet" href="{% static 'main/css/main.css'%}">
    </head>
    <body>
        <header class="custom-header py-3 px-5 d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center">
                <img src="{% static 'main/images/envira-brands.svg' %}" alt="icon" width="80" class="me-3">
                <h1 class="h2 mb-0">Делаем мир лучше</h1>
            </div>
            <div class="main-btns">
                <a href="{% url 'login' %}" class="btn btn-dark" style="width: 350px; font-size: 27px; padding: 5px;">Войти как администратор</a>
            </div>
        </header>
        <main>
            <div>
                <h1 style="font-size: 7rem">Здравствуйте!</h1>
                <p style="font-size: 3rem; margin-bottom: 7.5%;">У вас появилась проблема?<br>Напишите и мы поможем вам!</p>
                <a href="{% url 'create' %}" class="btn btn-primary btn-create"><b>Создать сообщение</b></a>
            </div> 
        </main>
    </body>
</html>

message/templates/message/make_a_message.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="icon" type="image/x-icon" href="{% static 'main\images\envira-brands.svg' %}">
        <title>Создать сообщение</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <link rel="stylesheet" href="{% static 'main/css/message_form.css'%}">
        <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&apikey=49577f47-020f-439f-b745-2e711ce62d5c"></script>
        <script src="{% static 'main\js\map.js'%}"></script>
        <script src="{% static 'main\js\display.js'%}"></script>
    </head>
    <body>
        <header class="custom-header py-3 px-5 d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center">
                <img src="{% static 'main/images/envira-brands.svg' %}" alt="icon" width="80" class="me-3">
                <h1 class="h2 mb-0">Делаем мир лучше</h1>
            </div>
            <div class="main-btns">
                <a href="{% url 'home' %}" class="btn btn-dark" style="width: 200px; height: 55px; font-size: 27px; padding: 5px;">На главную</a>
            </div>
        </header>
        <main>
            <div class="application_form">
                <h1 style="margin-bottom: 70px;">Оставьте ваше сообщение:</h1>
                <form method="post">
                    {% csrf_token %}
                    <div class="form_title">
                        <select id="id_title" name="title" class="custom-select" style="max-width: 300px;">
                            <option value="Choose theme">Выберите тему</option>
                            <option value="Fire">Пожар</option>
                            <option value="Fire in the forest">Пожар в лесу</option>
                            <option value="Road repairs">Ремонт дорог</option>
                            <option value="Clean garbage">Убрать мусор</option>
                            <option value="Street light">Уличное освещение</option>
                            <option value="Other">Другое (в первой строчке напишите тему)</option>
                        </select>
                        <div id="message" style="display:none; margin-top: 1.5%;">Это поле обязательно!</div>
                    </div><br>
                    {{form.mes_text}}<br>
                    {{form.ent_mail}}<br>
                    <p style="font-size: 20px; margin-right: 100%;">Координаты:</p>
                    <div style="display: flex; gap: 10px; height: 50px;">
                        {{ form.latitude }}
                        {{ form.longitude }}
                        <a id="openModal" class="btn btn-primary openmap" style="width: 100px;">Карта</a>
                    </div><br>
                    <button class="btn btn-success btn-lg" type="submit" id="submitButton" disabled>Отправить сообщение</button>
                </form>
            </div>
            <div id="modal" class="modal-overlay">
                <div id="mymap" class="maap"></div>
                <div class="modal-content">
                    <button id="closeModal" class="btn btn-dark close-btn">Закрыть</button>
                </div>
            </div>
            <script>
                document.getElementById('id_title').addEventListener('change', checkThemeSelection);
                window.onload = checkThemeSelection;
            </script>
        </main>
    </body>
</html>